NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Controllers/FixedByWeightByTotalController.cs
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Directory;
using Nop.Plugin.Shipping.FixedByWeightByTotal.Domain;
using Nop.Plugin.Shipping.FixedByWeightByTotal.Models;
using Nop.Plugin.Shipping.FixedByWeightByTotal.Services;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Services.Shipping;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Shipping.FixedByWeightByTotal.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class FixedByWeightByTotalController : BasePluginController
    {
        #region Fields

        private readonly CurrencySettings _currencySettings;
        private readonly FixedByWeightByTotalSettings _fixedByWeightByTotalSettings;
        private readonly ICountryService _countryService;
        private readonly ICurrencyService _currencyService;
        private readonly ILocalizationService _localizationService;
        private readonly IMeasureService _measureService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IShippingByWeightByTotalService _shippingByWeightService;
        private readonly IShippingService _shippingService;
        private readonly IStateProvinceService _stateProvinceService;
        private readonly IStoreService _storeService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly IWorkContext _workContext;
        private readonly MeasureSettings _measureSettings;

        #endregion

        #region Ctor

        public FixedByWeightByTotalController(CurrencySettings currencySettings,
            FixedByWeightByTotalSettings fixedByWeightByTotalSettings,
            ICountryService countryService,
            ICurrencyService currencyService,
            ILocalizationService localizationService,
            IMeasureService measureService,
            IPermissionService permissionService,
            ISettingService settingService,
            IShippingByWeightByTotalService shippingByWeightService,
            IShippingService shippingService,
            IStateProvinceService stateProvinceService,
            IStoreService storeService,
            IGenericAttributeService genericAttributeService,
            IWorkContext workContext,
            MeasureSettings measureSettings)
        {
            _currencySettings = currencySettings;
            _fixedByWeightByTotalSettings = fixedByWeightByTotalSettings;
            _countryService = countryService;
            _currencyService = currencyService;
            _localizationService = localizationService;
            _measureService = measureService;
            _permissionService = permissionService;
            _settingService = settingService;
            _shippingByWeightService = shippingByWeightService;
            _stateProvinceService = stateProvinceService;
            _shippingService = shippingService;
            _storeService = storeService;
            _genericAttributeService = genericAttributeService;
            _workContext = workContext;
            _measureSettings = measureSettings;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure(bool showtour = false)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            var model = new ConfigurationModel
            {
                LimitMethodsToCreated = _fixedByWeightByTotalSettings.LimitMethodsToCreated,
                ShippingByWeightByTotalEnabled = _fixedByWeightByTotalSettings.ShippingByWeightByTotalEnabled
            };

            //stores
            model.AvailableStores.Add(new SelectListItem { Text = "*", Value = "0" });
            foreach (var store in await _storeService.GetAllStoresAsync())
                model.AvailableStores.Add(new SelectListItem { Text = store.Name, Value = store.Id.ToString() });
            //warehouses
            model.AvailableWarehouses.Add(new SelectListItem { Text = "*", Value = "0" });
            foreach (var warehouses in await _shippingService.GetAllWarehousesAsync())
                model.AvailableWarehouses.Add(new SelectListItem { Text = warehouses.Name, Value = warehouses.Id.ToString() });
            //shipping methods
            foreach (var sm in await _shippingService.GetAllShippingMethodsAsync())
                model.AvailableShippingMethods.Add(new SelectListItem { Text = sm.Name, Value = sm.Id.ToString() });
            //countries
            model.AvailableCountries.Add(new SelectListItem { Text = "*", Value = "0" });
            var countries = await _countryService.GetAllCountriesAsync();
            foreach (var c in countries)
                model.AvailableCountries.Add(new SelectListItem { Text = c.Name, Value = c.Id.ToString() });
            //states
            model.AvailableStates.Add(new SelectListItem { Text = "*", Value = "0" });

            model.SetGridPageSize();

            //show configuration tour
            if (showtour)
            {
                var customer = await _workContext.GetCurrentCustomerAsync();
                var hideCard = await _genericAttributeService.GetAttributeAsync<bool>(customer, NopCustomerDefaults.HideConfigurationStepsAttribute);
                var closeCard = await _genericAttributeService.GetAttributeAsync<bool>(customer, NopCustomerDefaults.CloseConfigurationStepsAttribute);

                if (!hideCard && !closeCard)
                    ViewBag.ShowTour = true;
            }

            return View("~/Plugins/Shipping.FixedByWeightByTotal/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return Content("Access denied");

            //save settings
            _fixedByWeightByTotalSettings.LimitMethodsToCreated = model.LimitMethodsToCreated;
            await _settingService.SaveSettingAsync(_fixedByWeightByTotalSettings);

            return Json(new { Result = true });
        }

        [HttpPost]
        public async Task<IActionResult> SaveMode(bool value)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return Content("Access denied");

            //save settings
            _fixedByWeightByTotalSettings.ShippingByWeightByTotalEnabled = value;
            await _settingService.SaveSettingAsync(_fixedByWeightByTotalSettings);

            return Json(new { Result = true });
        }

        #region Fixed rate

        [HttpPost]
        public async Task<IActionResult> FixedShippingRateList(ConfigurationModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return await AccessDeniedDataTablesJson();

            var shippingMethods = (await _shippingService.GetAllShippingMethodsAsync()).ToPagedList(searchModel);

            var gridModel = await new FixedRateListModel().PrepareToGridAsync(searchModel, shippingMethods, () =>
            {
                return shippingMethods.SelectAwait(async shippingMethod => new FixedRateModel
                {
                    ShippingMethodId = shippingMethod.Id,
                    ShippingMethodName = shippingMethod.Name,

                    Rate = await _settingService
                        .GetSettingByKeyAsync<decimal>(string.Format(FixedByWeightByTotalDefaults.FixedRateSettingsKey, shippingMethod.Id)),
                    TransitDays = await _settingService
                        .GetSettingByKeyAsync<int?>(string.Format(FixedByWeightByTotalDefaults.TransitDaysSettingsKey, shippingMethod.Id))
                });
            });

            return Json(gridModel);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFixedShippingRate(FixedRateModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return Content("Access denied");

            await _settingService.SetSettingAsync(string.Format(FixedByWeightByTotalDefaults.FixedRateSettingsKey, model.ShippingMethodId), model.Rate, 0, false);
            await _settingService.SetSettingAsync(string.Format(FixedByWeightByTotalDefaults.TransitDaysSettingsKey, model.ShippingMethodId), model.TransitDays, 0, false);

            await _settingService.ClearCacheAsync();

            return new NullJsonResult();
        }

        #endregion

        #region Rate by weight

        [HttpPost]
        public async Task<IActionResult> RateByWeightByTotalList(ConfigurationModel searchModel, ConfigurationModel filter)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageShippingSettings))
                return await AccessDeniedDataTablesJson();

            //var records = _shippingByWeightService.GetAll(command.Page - 1, command.PageSize);
            var records = await _shippingByWeightService.FindRecordsAsync(
              pageIndex: searchModel.Page - 1,
              pageSize: searchModel.PageSize,
              storeId: filter.SearchStoreId,
              warehouseId: filter.SearchWarehouseId,

NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Views/AddRateByWeightByTotalPopup.cshtml
@{
    Layout = "_AdminPopupLayout";
}
@model Nop.Plugin.Shipping.FixedByWeightByTotal.Models.ShippingByWeightByTotalModel

<form asp-controller="FixedByWeightByTotal" asp-action="AddRateByWeightByTotalPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Common.AddNew")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
        </div>
    </div>

    <section class="content">
		<div class="container-fluid">
			<div class="form-horizontal">
				@await Html.PartialAsync("~/Plugins/Shipping.FixedByWeightByTotal/Views/_CreateOrUpdateRateByWeightByTotal.cshtml", Model)
			</div>
		</div>
    </section>
</form>

NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Views/Configure.cshtml
@model Nop.Plugin.Shipping.FixedByWeightByTotal.Models.ConfigurationModel
@using Nop.Web.Framework.Models.AdminAreaTour

@{
    Layout = "_ConfigurePlugin";

    //tour step
    ViewBag.TourStep = TourStep.ShippingManual;
}

@await Html.PartialAsync("_AdminTour")

<div class="row pb-3">
    <div class="col-md-3">
        <div class="onoffswitch">
            <input type="checkbox" name="onoffswitch" class="onoffswitch-checkbox" id="advanced-settings-mode" checked="@Model.ShippingByWeightByTotalEnabled">
            <label class="onoffswitch-label" for="advanced-settings-mode">
                <span class="onoffswitch-inner"
                      data-locale-basic="@T("Plugins.Shipping.FixedByWeightByTotal.Fixed")"
                      data-locale-advanced="@T("Plugins.Shipping.FixedByWeightByTotal.ShippingByWeight")"></span>
                <span class="onoffswitch-switch"></span>
            </label>
        </div>
    </div>
    <div class="col-md-9">
        <div class="float-right">
            <a asp-controller="Shipping" asp-action="Methods" class="btn btn-primary" id="manage-shipping-methods-button">
                <i class="fas fa-truck"></i>
                @T("Admin.Configuration.Shipping.Methods.Manage")
            </a>
            <a asp-controller="Shipping" asp-action="Restrictions" class="btn btn-primary">
                <i class="fas fa-globe"></i>
                @T("Admin.Configuration.Shipping.Restrictions")
            </a>
        </div>
    </div>
</div>

<script>
    function checkAdvancedSettingsMode(advanced) {
        if (advanced) {
            $("body").addClass("advanced-settings-mode");
            $("body").removeClass("basic-settings-mode");
        } else {
            $("body").removeClass("advanced-settings-mode");
            $("body").addClass("basic-settings-mode");
        }
    }

    checkAdvancedSettingsMode($("#advanced-settings-mode").is(':checked'));
    $(document)
        .ready(function() {
            $("#advanced-settings-mode")
                .click(function() {
                    checkAdvancedSettingsMode($(this).is(':checked'));

                    var postData = {
                        value: $(this).is(':checked')
                    };
                    addAntiForgeryToken(postData);

                    $.ajax({
                        cache: false,
                        url: "@Url.Action("SaveMode", "FixedByWeightByTotal")",
                        type: "POST",
                        data: postData,
                        dataType: "json",
                        error: function (jqXHR, textStatus, errorThrown) {
                            $("#saveModeAlert").click();
                        }
                    });
                    ensureDataTablesRendered();
                });
        });
</script>

<nop-alert asp-alert-id="saveModeAlert" asp-alert-message="@T("Admin.Common.Alert.Save.Error")" />

@await Html.PartialAsync("~/Plugins/Shipping.FixedByWeightByTotal/Views/_FixedRate.cshtml")
@await Html.PartialAsync("~/Plugins/Shipping.FixedByWeightByTotal/Views/_ByWeightByTotal.cshtml", Model)

NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Views/EditRateByWeightByTotalPopup.cshtml
@{
    Layout = "_AdminPopupLayout";
}
@model Nop.Plugin.Shipping.FixedByWeightByTotal.Models.ShippingByWeightByTotalModel

<form asp-controller="FixedByWeightByTotal" asp-action="EditRateByWeightByTotalPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Common.Edit")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("~/Plugins/Shipping.FixedByWeightByTotal/Views/_CreateOrUpdateRateByWeightByTotal.cshtml", Model)
        </div>
    </div>
</form>

NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Views/_CreateOrUpdateRateByWeightByTotal.cshtml
@model Nop.Plugin.Shipping.FixedByWeightByTotal.Models.ShippingByWeightByTotalModel
@using Nop.Web.Framework.Extensions

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}

<script>
    $(document).ready(function () {
        $("#@Html.IdFor(model => model.CountryId)").change(function () {
            var selectedItem = $(this).val();
            var ddlStates = $("#@Html.IdFor(model => model.StateProvinceId)");
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.Action("GetStatesByCountryId", "Country"))",
                data: {
                    "countryId": selectedItem,
                    "addAsterisk": "true"
                },
                success: function (data, textStatus, jqXHR) {
                    ddlStates.html('');
                    $.each(data, function (id, option) {
                        ddlStates.append($('<option></option>').val(option.id).html(option.name));
                    });
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    $("#getStatesByCountryIdAlert").click();
                }
            });
        });
    });
</script>

<div class="cards-group">
    <div class="card card-default card-popup">
        <div class="card-body">
            <div class="form-group row" @(Model.AvailableStores.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                <div class="col-sm-3">
                    <nop-label asp-for="StoreId" />
                </div>
                <div class="col-sm-9">
                    <nop-select asp-for="StoreId" asp-items="Model.AvailableStores" />
                    <span asp-validation-for="StoreId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="WarehouseId" />
                </div>
                <div class="col-sm-9">
                    <nop-select asp-for="WarehouseId" asp-items="Model.AvailableWarehouses" />
                    <span asp-validation-for="WarehouseId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="CountryId" />
                </div>
                <div class="col-sm-9">
                    <nop-select asp-for="CountryId" asp-items="Model.AvailableCountries" />
                    <span asp-validation-for="CountryId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="StateProvinceId" />
                </div>
                <div class="col-sm-9">
                    <nop-select asp-for="StateProvinceId" asp-items="Model.AvailableStates" />
                    <span asp-validation-for="StateProvinceId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="Zip" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="Zip" />
                    <span asp-validation-for="Zip"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="ShippingMethodId" />
                </div>
                <div class="col-sm-9">
                    <nop-select asp-for="ShippingMethodId" asp-items="Model.AvailableShippingMethods" />
                    <span asp-validation-for="ShippingMethodId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="WeightFrom" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="WeightFrom" asp-postfix="@Model.BaseWeightIn" />
                    <span asp-validation-for="WeightFrom"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="WeightTo" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="WeightTo" asp-postfix="@Model.BaseWeightIn" />
                    <span asp-validation-for="WeightTo"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="OrderSubtotalFrom" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="OrderSubtotalFrom" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="OrderSubtotalFrom"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="OrderSubtotalTo" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="OrderSubtotalTo" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="OrderSubtotalTo"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="AdditionalFixedCost" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="AdditionalFixedCost" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="AdditionalFixedCost"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="LowerWeightLimit" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="LowerWeightLimit" />
                    <span asp-validation-for="LowerWeightLimit"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="RatePerWeightUnit" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="RatePerWeightUnit" asp-postfix="@Model.PrimaryStoreCurrencyCode" />
                    <span asp-validation-for="RatePerWeightUnit"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="PercentageRateOfSubtotal" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="PercentageRateOfSubtotal" />
                    <span asp-validation-for="PercentageRateOfSubtotal"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-3">
                    <nop-label asp-for="TransitDays" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="TransitDays" />
                    <span asp-validation-for="TransitDays"></span>
                </div>
            </div>
        </div>
    </div>
</div>
<nop-alert asp-alert-id="getStatesByCountryIdAlert" asp-alert-message="@T("Admin.Common.Alert.States.Failed")" />

NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.Shipping.FixedByWeightByTotal/Views/_FixedRate.cshtml
@using Nop.Plugin.Shipping.FixedByWeightByTotal.Models
@using Nop.Web.Framework.Models.DataTables
<div class="cards-group basic-setting">
    <div class="card card-default">
        <div class="card-body">
            @await Html.PartialAsync("Table", new DataTablesModel
            {
                Name = "shipping-rate-grid",
                UrlRead = new DataUrl("FixedShippingRateList", "FixedByWeightByTotal", null),
                UrlUpdate = new DataUrl("UpdateFixedShippingRate", "FixedByWeightByTotal", null),
                Length = Model.PageSize,
                LengthMenu = Model.AvailablePageSizes,
                ColumnCollection = new List<ColumnProperty>
                {
                    new ColumnProperty(nameof(FixedRateModel.ShippingMethodName))
                    {
                        Title = T("Plugins.Shipping.FixedByWeightByTotal.Fields.ShippingMethod").Text
                    },
                    new ColumnProperty(nameof(FixedRateModel.Rate))
                    {
                        Title = T("Plugins.Shipping.FixedByWeightByTotal.Fields.Rate").Text,
                        Width = "200",
                        Editable = true,
                        EditType = EditType.Number	 
                    },
                    new ColumnProperty(nameof(FixedRateModel.TransitDays))
                    {
                        Title = T("Plugins.Shipping.FixedByWeightByTotal.Fields.TransitDays").Text,
                        Width = "200",
                        Editable = true,
                        EditType = EditType.Number	 
                    },
                    new ColumnProperty(nameof(FixedRateModel.ShippingMethodId))
                    {
                        Title = T("Admin.Common.Edit").Text,
                        Width = "200",
                        ClassName =  NopColumnClassDefaults.Button,
                        Render = new RenderButtonsInlineEdit()
                    }
                }
            })
        </div>
    </div>
</div>