NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.MultiFactorAuth.GoogleAuthenticator/Controllers/GoogleAuthenticatorController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Plugin.MultiFactorAuth.GoogleAuthenticator.Models;
using Nop.Plugin.MultiFactorAuth.GoogleAuthenticator.Services;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.MultiFactorAuth.GoogleAuthenticator.Controllers
{
    [AutoValidateAntiforgeryToken]
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public class GoogleAuthenticatorController : BasePluginController
    {
        #region Fields

        private readonly GoogleAuthenticatorService _googleAuthenticatorService;
        private readonly GoogleAuthenticatorSettings _googleAuthenticatorSettings;
        private readonly ICustomerService _customerService;
        private readonly IGenericAttributeService _genericAttributeService;        
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IWorkContext _workContext;


        #endregion

        #region Ctor 

        public GoogleAuthenticatorController(GoogleAuthenticatorService googleAuthenticatorService,
            GoogleAuthenticatorSettings googleAuthenticatorSettings,
            ICustomerService customerService,
            IGenericAttributeService genericAttributeService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IWorkContext workContext
            )
        {
            _googleAuthenticatorService = googleAuthenticatorService;
            _googleAuthenticatorSettings = googleAuthenticatorSettings;
            _customerService = customerService;
            _genericAttributeService = genericAttributeService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _workContext = workContext;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageMultifactorAuthenticationMethods))
                return AccessDeniedView();

            //prepare model
            var model = new ConfigurationModel
            {
                QRPixelsPerModule = _googleAuthenticatorSettings.QRPixelsPerModule,
                BusinessPrefix = _googleAuthenticatorSettings.BusinessPrefix                
            };
            model.GoogleAuthenticatorSearchModel.HideSearchBlock = await _genericAttributeService
                .GetAttributeAsync<bool>(await _workContext.GetCurrentCustomerAsync(), GoogleAuthenticatorDefaults.HideSearchBlockAttribute);

            return View("~/Plugins/MultiFactorAuth.GoogleAuthenticator/Views/Configure.cshtml", model);
        }

        [HttpPost]        
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageMultifactorAuthenticationMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            //set new settings values
            _googleAuthenticatorSettings.QRPixelsPerModule = model.QRPixelsPerModule;
            _googleAuthenticatorSettings.BusinessPrefix = model.BusinessPrefix;
            await _settingService.SaveSettingAsync(_googleAuthenticatorSettings);

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        [HttpPost]
        public async Task<IActionResult> GoogleAuthenticatorList(GoogleAuthenticatorSearchModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageMultifactorAuthenticationMethods))
                return AccessDeniedView();

            //get GoogleAuthenticator configuration records
            var configurations = await _googleAuthenticatorService.GetPagedConfigurationsAsync(searchModel.SearchEmail,
                searchModel.Page - 1, searchModel.PageSize);
            var model = new GoogleAuthenticatorListModel().PrepareToGrid(searchModel, configurations, () =>
            {
                //fill in model values from the configuration
                return configurations.Select(configuration => new GoogleAuthenticatorModel
                {
                    Id = configuration.Id,
                    Customer = configuration.Customer,
                    SecretKey = configuration.SecretKey
                });
            });

            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> GoogleAuthenticatorDelete (GoogleAuthenticatorModel model)
        {
            if (!ModelState.IsValid)
                return ErrorJson(ModelState.SerializeErrors());

            //delete configuration
            var configuration = await _googleAuthenticatorService.GetConfigurationByIdAsync(model.Id);
            if (configuration != null)
            {
                await _googleAuthenticatorService.DeleteConfigurationAsync(configuration);
            }
            var customer = await _customerService.GetCustomerByEmailAsync(configuration.Customer) ??
                await _customerService.GetCustomerByUsernameAsync(configuration.Customer);

            if (customer != null)
                await _genericAttributeService.SaveAttributeAsync(customer, NopCustomerDefaults.SelectedMultiFactorAuthenticationProviderAttribute, string.Empty);

            return new NullJsonResult();
        }

        #endregion
    }
}

NopCommerce/Nop450/nopStationPlugin_450/Plugins/Nop.Plugin.MultiFactorAuth.GoogleAuthenticator/Views/Configure.cshtml
@model ConfigurationModel
@inject Nop.Core.IWebHelper webHelper

@{
    Layout = "_ConfigurePlugin";
    var hideSearchBlock = Model.GoogleAuthenticatorSearchModel.HideSearchBlock;
}

<form asp-controller="GoogleAuthenticator" asp-action="Configure" method="post">    
    <selection class="content">
        <div class="container-fluid">
            <div class="card card-default">
                <div class="card-body">
                    <p>
                        @Html.Raw(string.Format(T("Plugins.MultiFactorAuth.GoogleAuthenticator.Instructions").Text, webHelper.GetStoreLocation()))
                    </p>
                    <hr/>
                    <div class="form-group row">                    
                        <div class="col-md-3">
                            <nop-label asp-for="BusinessPrefix" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="BusinessPrefix" />
                            <span asp-validation-for="BusinessPrefix"></span>
                        </div>
                    </div>
                    <div class="form-group row">                    
                        <div class="col-md-3">
                            <nop-label asp-for="QRPixelsPerModule" />
                        </div>
                        <div class="col-md-9">
                            <nop-editor asp-for="QRPixelsPerModule" />
                            <span asp-validation-for="QRPixelsPerModule"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-9 offset-md-3">
                            <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card card-default card-search">
                <div class="card-body">
                    <div class="row search-row @(!Model.GoogleAuthenticatorSearchModel.HideSearchBlock ? "opened" : "")" data-hideAttribute="@GoogleAuthenticatorDefaults.HideSearchBlockAttribute">
                        <div class="search-text">@T("Admin.Common.Search")</div>
                        <div class="icon-search"><i class="fas fa-search" aria-hidden="true"></i></div>
                        <div class="icon-collapse"><i class="far fa-angle-@(!hideSearchBlock ? "up" : "down")" aria-hidden="true"></i></div>
                    </div>
                    <div class="search-body @(Model.GoogleAuthenticatorSearchModel.HideSearchBlock ? "closed" : "")">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="@Model.GoogleAuthenticatorSearchModel.SearchEmail" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="@Model.GoogleAuthenticatorSearchModel.SearchEmail" />
                                    </div>
                                </div>                            
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-center col-12">
                                <button type="button" id="search-customers" class="btn btn-primary btn-search">
                                    <i class="fas fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card card-default">
                <div class="card-body">
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "googleguthenticator-grid",
                        SearchButtonId = "search-customers",
                        UrlRead = new DataUrl("GoogleAuthenticatorList", "GoogleAuthenticator", null),
                        UrlDelete = new DataUrl("GoogleAuthenticatorDelete", "GoogleAuthenticator", null),
                        Length = Model.GoogleAuthenticatorSearchModel.PageSize,
                        LengthMenu = Model.GoogleAuthenticatorSearchModel.AvailablePageSizes,
                        Filters = new List<FilterParameter>
                        {
                            new FilterParameter(nameof(GoogleAuthenticatorSearchModel.SearchEmail), nameof(GoogleAuthenticatorSearchModel))
                        },
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(nameof(GoogleAuthenticatorModel.Customer))
                            {
                                Title = T("Plugins.MultiFactorAuth.GoogleAuthenticator.Fields.Customer").Text
                            },
                            new ColumnProperty(nameof(GoogleAuthenticatorModel.Id))
                            {
                                Title = T("Admin.Common.Delete").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.Button,
                                Render = new RenderButtonRemove(T("Admin.Common.Delete").Text)
                            }
                        }
                    })
                </div>
            </div>
        </div>
    </selection>
</form>